### ISSUE TITLE
Coordinate with rustybuzz?

### ISSUE THREAD

**Issue by twardoch** [wrl/otf-fea-rs#1]
https://github.com/wrl/otf-fea-rs/ is a Rust-based compiler of FEA into GSUB/GPOS, while https://github.com/RazrFalcon/rustybuzz is a Rust-based OT shaper. 

Perhaps @wrl and @RazrFalcon could somehow coordinate so that the two libraries can interoperate. No specific idea yet but I can well imagine this to be beneficial.

**Comment by twardoch** [comment]
There is also https://github.com/RazrFalcon/ttf-parser

**Comment by davelab6** [comment]
@raphlinus and @cmyr and @ctrlcctrlv may be interested in these ideas : )

**Comment by wrl** [comment]
Absolutely. Raph and I are regularly coördinating on what kind of API and data model they'll need in Runebender. As for the shaping which RustyBuzz handles, I'm not sure what the specific plans are.

I'll copy/paste the response I gave in the corresponding ticket which was raised on RustyBuzz:
> While there is certainly some common ground between otf-fea-rs and RustyBuzz, I don't think the overlap is massive. I think the biggest thing would be the parsing/loading of the more advanced OpenType tables (notably, GPOS and GSUB). The Runebender project is already interested in utilising some of the otf-fea-rs code for this, so in the short/mid-term I will be breaking those components out into a reusable state.
> 
> Of note, though, is that since otf-fea-rs is designed to both read _and_ write TTF/OTF files, the data model is not as efficient as it could be from a read-only point of view. For example, ttf-parser is zero-allocation, which otf-fea-rs cannot be without splitting the read and write data models. With that said, I'm of course interested in using the most optimal data structures while balancing these concerns.

**Comment by wrl** [comment]
And I'll also close this for now since RazrFalcon isn't presently interested.
